### ISSUE TITLE
BUCKET_HOST vs. BUCKET_SERVICE for cluster provided S3 services

### ISSUE THREAD

**Issue by guymguym** [kube-object-storage/lib-bucket-provisioner#130]
Hi @jeffvance @copejon 
CC: @dannyzaken @tamireran @nimrod-becker 

The current provisioner requires to resolve the service to a single address that is assigned to the `BUCKET_HOST` and `BUCKET_PORT` in the configmap. This makes sense for a global service like AWS/Google/Azure endpoints.

However when the S3 endpoint is serving inside the cluster, there are multiple ways that clients may need to connect to the service - either using internal-DNS `<service-name>.<namespace>` or using nodePort, or using external load balancer, or using a route/ingress, etc. It seems weird that every OBC should be aware of the client network requirements. 

I would expect that in this case the configmap will include just the `BUCKET_SERVICE_NAME` and `BUCKET_SERVICE_NAMESPACE` so that the OBC provisioner can assign a service to the client, and the client can decide on which service endpoint to use.

Thoughts?

**Comment by copejon** [comment]
That's a great point.  In its infancy, the library was designed under the assumption of a single endpoint for an in-cluster object store.  Services are probably the most common endpoint used, but ultimately the library is agnostic to which API resource, if any is used to form the connection.  However, it also does not provide a mechanism for preferencing one route over another.

This could be addressed via StorageClasses.  For every route to the object store, a StorageClass could be defined.  This allows the library to remain agnostic to the endpoint and the ConfigMap data structure remains unchanged.  The provisioner would be responsible ensuring the appropriate endpoint is returned respective of the StorageClass.  e.g.

1 Class for Ingress
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: object-store-ingress
provisioner: bucket.io/provisioner
parameters:
  connectionType: ingress
```
1 Class for Service
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: object-store-service
provisioner: bucket.io/provisioner
parameters:
  connectionType: service
```

A possible downside is that now the developer/cluster-user has to know which one they want, which may not be acceptable.
