### ISSUE TITLE
Additional Config was missing in OBC spec

### ISSUE THREAD

**Issue by thotz** [kube-object-storage/lib-bucket-provisioner#190]
I have used below CR for creating obc for adding support for [quota](https://github.com/rook/rook/issues/5274) in OBC via additional config

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-delete-bucket
spec:
  # To create a new bucket specify either `bucketName` or 
  # `generateBucketName` here. Both cannot be used. To access
  # an existing bucket the bucket name needs to be defined in
  # the StorageClass referenced here, and both `bucketName` and
  # `generateBucketName` must be omitted in the OBC.
  #bucketName: 
  generateBucketName: ceph-bkt
  storageClassName: rook-ceph-delete-bucket
  AdditionalConfig:
    maxObjects: 1000
    maxSize: 2
```
Apparently above info is missing in `ObjectBucketClaimSpec` and not able to fetch in the rook operator code
